### ISSUE TITLE
when creating the layout, the user should be able to specify whether to read (metadata) or not

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-matlab#16]
Right now most of the metadata is automatically read (bval, bvec, events, channels), but other metadata is not read (headshape, photo, etc.). I think this mainly distinguishes between the metadata being in `tsv` files (which are read) versus another format (which are not read).

I think it would be nice to make this configurable, so that the user would know whether he can always expect a MATLAB struct or a string pointing to a filename.

**Comment by gllmflndn** [comment]
I agree. I was not sure what to do in a first instance, that's why there are all these `% ?` in the code. Not only is this inconsistent but it might affect significantly the parsing time and the amount of memory required.
Adding an option in `BIDS.layout` makes sense. I will factor that in with pull request #11. Do you have in mind something like reading everything or nothing, or something more fine-grained?

**Comment by robertoostenveld** [comment]
I am actually not sure yet... I will try it out on more datasets to see what feels right.

**Comment by robertoostenveld** [comment]
Actually I think that it would be fine to keep it as it is, i.e. whenever it relates to a tsv or json file, that it returns the content.
