### ISSUE TITLE
Feature request: function to add new fields to `dataset_description.json`

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#177]
When creating derivatives, BIDS requires to add `GeneratedBy` field. On itself it is not difficult, but it would nice to have a simple centralised script to generate such fields. 

Something like:
```
update_description(BIDS, fieldname, data, append)
```
with append a bool that decides if field will be appended to existing field, or will replace it.

**Comment by Remi-Gau** [comment]
Very mcuh agreed.

This is part of creating / enhancing the "writing" aspects of bids-matlab.

This issue is subset of some the feature suggestions from  @bmdeen in #79.

Will also have start having a look into this, as it could help create some utilities that could be useful for other things later.
