### ISSUE TITLE
bids.util.jsonencode opts.Indent not working

### ISSUE THREAD

**Issue by bmdeen** [bids-standard/bids-matlab#192]
After pulling the latest version of bids-matlab today, the functionality of opts.Indent is no longer working for me. Specifically, I've been using the following code to write json files with tab indentation:

`jsonOpts.Indent = '\t';
bids.util.jsonencode(jsonPath,jsonStruct,jsonOpts);`

I'm using matlab 2020b on a Mac (10.15.7). I have bids-matlab-tools installed, and I suspect that this function was previously calling bids-matlab-tools' jsonwrite (which I can still use with jsonOpts.Indent), and is now defaulting to MATLAB's built-in jsonencode function, which doesn't process opts.Indent as an argument.

**Comment by Remi-Gau** [comment]
hey @bmdeen 

yeah I know and that's a consequence of #178.

https://github.com/bids-standard/bids-matlab/pull/178#discussion_r583622715

In brief we changed the priority order used by `bids.util.jsonencode` to know which function to write JSON.

So now it first checks for octave or matlab functions to write jsons. If it finds one then it uses that. But matlab's son writing gives a very human unfriendly output I agree...

as pointed by @gllmflndn we could now add support the recent matlab "prettyprint" but that will still leave a lot of users with ugly json
https://nl.mathworks.com/help/matlab/ref/jsonencode.html#bvb7dgc-2

**Comment by Remi-Gau** [comment]
In the meantime, one tip that I use: having a code formatted set up on my code editor (vs code) to make sure that my code, markdown and json are reformatted on save.

In my case I use prettier:

https://prettier.io/

**Comment by bmdeen** [comment]
Got it, thanks. For the sake of backward compatibility, would it be reasonable to prioritize JSONio over matlab's jsonencode only when opts.Indent is specified? This might be a bit inelegant code-wise, but would at least give users with earlier versions of matlab some direct way to write indented json files.

**Comment by Remi-Gau** [comment]
yeah that could be a "nice" work around actually: for something like this I'd rather have elegant json output than elegant code.
 
 users are more likely to read the json than the code. :-)
 
 will try to work on this: but bids-matlab won't be on my plate till next week at least.

**Comment by gllmflndn** [comment]
Hello @bmdeen and @Remi-Gau 

From the beginning, the simplest approach regarding JSON would have been to include JSONio in bids-matlab while MATLAB and Octave get their act together. The downside is that the decoding is a MEX file and it's much easier to distribute a tool when one doesn't have to worry about compilation, hence the current complicated approach (and the fact that, when available, MATLAB and Octave have faster implementations). 

`jsonwrite` is pure MATLAB though so perhaps the solution here would be to have it copied in `bids.util.jsonencode` so that it would be used at all times. What do you think?

**Comment by bmdeen** [comment]
That solution makes sense to me.
