### ISSUE TITLE
Supported Matlab versions?

### ISSUE THREAD

**Issue by apjanke** [bids-standard/bids-matlab#22]
Hi, BIDS folks,

Could you document which versions of Matlab are supported by bids-matlab?

And to what degree is Octave supported? Is bids-matlab strictly limiting itself to features & functions available in Octave as well as Matlab? And if so, which versions of Octave are supported?

**Comment by gllmflndn** [comment]
Hi @apjanke,

The original code which `bids-matlab` is based upon was written to work with all MATLAB versions since R2007a and 'recent' Octave (4.2.2 onwards).

This is now to be decided for `bids-matlab` so I hope others will chime in. I would argue R2014a for MATLAB. For Octave we are limited by the version that users easily have access to with their package manager. Still, we can be forward-looking and make sure that we will implement in Octave missing features that will be used in this project.

**Comment by robertoostenveld** [comment]
MATLAB R2014a and up would work for me (i.e. for FieldTrip). I don't know enough about Octave versioning to give an informed opinion about that.

**Comment by robertoostenveld** [comment]
Related to this: Last week I was at http://practicalmeeg2019.org where we did hands-on sessions with ~40 people attending the session I was chairing. R2014 (a or b) was the oldest one that I encountered there, some from 2015, and most 2017-2018.

**Comment by apjanke** [comment]
> MATLAB R2014a and up would work for me (i.e. for FieldTrip).

Sounds good to me.

> I don't know enough about Octave versioning to give an informed opinion about that.

I work with Octave. I'd recommend Octave 4.2.2 onwards like you're doing now. 4.2.x is the latest version available in many Linux package managers. So it's in common use. And 4.4.1 is the latest Octave version that works stably on macOS.
