### ISSUE TITLE
Better/proper/cleaner/easier handling of multi-session dataset

### ISSUE THREAD

**Issue by ChristophePhillips** [bids-standard/bids-matlab#63]
As far as I can see right now, each session from the subjects will appear as a separate 'subject' after reading in the layout of the BIDS dataset. See [this line](https://github.com/bids-standard/bids-matlab/blob/master/%2Bbids/layout.m#L141) in `layout.m`.

For example, a 134 subjects study, where each subject underwent scanning (or data acquisition) over 2 sessions, `subjects` will be as a `1 x 268` sub-structure array and the `sessions` field is nor populated:
````
oBIDS = 

             dir: 'path_to_BIDS_dataset'
     description: [1x1 struct]
        sessions: {}
           scans: [0x0 struct]
            sess: [0x0 struct]
    participants: [1x1 struct]
        subjects: [1x268 struct]
````
while I would expect to have `subjects` sub-structure array of size `134 x 2` and the `sessions` field as a `134 x 1` cell array (or something similar):

````
BIDS = 

             dir: 'path_to_BIDS_dataset'
     description: [1x1 struct]
        sessions: {1x134 cell}
           scans: [0x0 struct]
            sess: [0x0 struct]
    participants: [1x1 struct]
        subjects: [134x2 struct]
````

I have slightly update the `layout.m` function to do this but there remain a few open questions on how exactly describe multi-session dataset:
- what about the case where subjects may have a different number of sessions? 
  - should the `subjects` field be a `Nsubj x Nsess` structure array, with some of these empty when the session is missing?  
  ➡️ this is straightforward and in line with how modalities are left empty if not present.
  - the `subjects` field could also be `Nsubj x 1` cell array, each containing a `1 x Nsess_subj` array of `subjects` structure? 
  ➡️ more complicated to handle IMO.
- what about listing the sessions in the field `sessions`?
  - just a cell array of the unique sessions in the data set, i.e. a `1 x Nsess` cell array? 
  ➡️ minimalist option, which may well be sufficient.
  - `Nsubj x 1` cell array with each cells containing the  `1 x Nsess_subj` cell array for that specific subject? 
  ➡️ more comprehensive but more complicated to handle (that's what I did in my update for no specific reason actually)
  - a `Nsubj x Nsess` cell array with some cells left empty when the session is missing? 
  ➡️ this feels really redundant.

where `Nsess` is the total number of different sessions and `Nsess_subj` the number of session for a specific subject.

**Comment by Remi-Gau** [comment]
I kinda of agree with having a cleaner structure where `nume(BIDS.subject)` gives you the number of subject and not some weird combination of number of subjects times number of sessions.

Though I would say that as long as `query` returns the correct value then it is OKish. Did you have to udate the layout because query was giving you weird results or because query could not do what you wanted?

**Comment by robertoostenveld** [comment]
the session-level being optional in BIDS has caused me many headaches. I tend to solve it by always imposing a session-level, even when there is only a single session. But I am not sure that a table (or array, matrix) will solve it in a clean fashion.

e.g., imagine this

```
bidsroot/
├── sub-01
│   ├── ses-a
│   └── ses-b
├── sub-02
│   ├── ses-b
│   └── ses-c
└── sub-03
    └── ses-d
```

The BIDS structure on disk is a tree-like hierarchy. That is also how I would like to use it in MATLAB, hence I would prefer nested structures.

**Comment by gllmflndn** [comment]
I think there are two parts to this comment:

- The layout of the `BIDS` variable is internal. This means that, as a user, you should not access information by referencing the content of the BIDS variable but use `bids.query` instead. If there is some information you don't manage to access through a query, this means we need to introduce a new functionality to `bids.query` (or other high level function). I had a few iterations like this with @CPernet when he was testing `spm_BIDS`.
We could enforce this by using a class (see #39) - I would prefer not to, in order to keep the code simple. But what I am trying to say here is that the format chosen for the BIDS structure should not be of any concern for a user and you should never do something like `numel(BIDS.subject)` and instead always do ` numel(bids.query(BIDS,'subjects'))`.
- Now, about the choice of the internal structure (for developers): if I remember correctly, I considered different approaches - this might be reflected in the history of this repository (the `sess` field might be a breadcrumb). The issue is indeed that sessions are optional and can vary across subjects. At the end of the day, I found it easier to flatten the nested structure, making it closer to a database. It is easier and faster to traverse an array than a nested structure.

Of course, this is only my personal opinion and an explanation of why things are as they are; everything is open for discussion and changes.

**Comment by Remi-Gau** [comment]
>     * But what I am trying to say here is that the format chosen for the BIDS structure should not be of any concern for a user and you should never do something like `numel(BIDS.subject)` and instead always do ` numel(bids.query(BIDS,'subjects'))`.

+1 for some encapsulation of this.

Another issue that we might want to keep in mind (at least in the long term) is how bids-matlab handles very large datasets.

An issue that pybids has "faced": https://github.com/bids-standard/pybids/issues/609

**Comment by Remi-Gau** [comment]
>     * The layout of the `BIDS` variable is internal. This means that, as a user, you should not access information by referencing the content of the BIDS variable but use `bids.query` instead. If there is some information you don't manage to access through a query, this means we need to introduce a new functionality to `bids.query` (or other high level function). I had a few iterations like this with @CPernet when he was testing `spm_BIDS`.
>       We could enforce this by using a class (see #39) - I would prefer not to, in order to keep the code simple. But what I am trying to say here is that the format chosen for the BIDS structure should not be of any concern for a user and you should never do something like `numel(BIDS.subject)` and instead always do ` numel(bids.query(BIDS,'subjects'))`.

Was just thinking that if we decide to stick to this approach of not wanting to "let" users get their hands dirty and dive into the internal of the `BIDS` variable, we should somehow make it VERY explicit that this is the "philosophy" of the toolbox so as to incite users to ask for more features to be added to `query` or somewhere else.

**Comment by ChristophePhillips** [comment]
Arf, I see now where my confusion comes from 
> The layout of the BIDS variable is internal.

and I am pleading guilty of trying to directly use the BIDS variable for my data handling.
It was too tempting not to, like an open box of chocolate open in front of you that you should not touch and taste, and others might be tempted too. In my case I had the same/similar issue as mentioned in the bug-issue #65, where sessions and modalities are not filtered as expected. So I switched to the straightforward approach of manipulating the BIDS structure for my purpose.

I agree though that it would be safer to keep the BIDS variable internal and use a specific query function.

**Comment by Remi-Gau** [comment]
Well I think that just means that we need to improve the documentation too. :-)

**Comment by Remi-Gau** [comment]
@all-contributors please add @ChristophePhillips for ideas
