### ISSUE TITLE
BIDS viewer in MATLAB

### ISSUE THREAD

**Issue by tanguyduval** [bids-standard/bids-matlab#7]
Hi all,

Thank you for this very handy repo. This issue is to make you aware of my contributions since I'm using BIDS with MATLAB for nearly a year now:

1. I created this BIDS viewer for MATLAB based on the excellent imtool3D viewer:
https://github.com/tanguyduval/imtool3D_td
**There is a dependency with the excellent dicm2nii toolbox for loading files**
You can call it using imtool3D_BIDS
I am using this bids-matlab repo in order to parse the BIDS folder. But I had to make small changes to parse my BIDS folder since it was too sensitive to errors in .tsv files.

2. I recently collaborated with xiangruili to include an interactive BIDS converter in dicm2nii.

It would be great to have your feedbacks on the viewer and converter. And I would be very pleased to add these tools in bids-standard.

Best,
Tanguy

**Comment by gllmflndn** [comment]
Hi @tanguyduval,

Many thanks for this, it would be great if we could incorporate your changes in `bids-matlab` whenever possible:
https://github.com/tanguyduval/imtool3D_td/commits/master/External/bids-matlab
Best would be to open specific issues/pull requests so that they can be discussed. For example, `dataset_description.json` is a mandatory file
https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#dataset_descriptionjson
so we will have to decide what is the outcome of the parsing if a dataset is not fully BIDS-compliant.

Concerning `imtool3D` and `dicm2nii`, while indeed looking excellent, they are probably out of scope for this repository. Maybe we should list downstream projects using `bids-matlab` in `README.md` or use the wiki. What are the requirements in terms of MATLAB versions (and toolboxes) and are they compatible with Octave? The aim for `bids-matlab` is to put the requirement threshold bar as low as possible.

**Comment by tanguyduval** [comment]
Hi @gllmflndn,

I propose to add an option in bids.layout for tolerant parsing. (e.g. `bids.layout('pathtobids','-t')`)
What do you think?

Both the viewer and the converter require Matlab. Some efforts have been made for compatibility with R2014a and for the absence of toolbox dependencies.
However, for Octave compatibility, it could be done... but I cannot invest that much time
Adding the link to the readme seems good to me.

Best,
Tanguy

**Comment by gllmflndn** [comment]
OK, let's add an option mechanism through `bids.layout(root, parameter, value, ...)`
Can you list what `tolerant` parsing involves for you? missing `dataset_description.json`, dodgy `tsv` files?
Thanks!

**Comment by gllmflndn** [comment]
This is now being dealt with in #11 and #13 so closing the issue here.
