### ISSUE TITLE
implement unit tests and set up continuous integration

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#9]
Mentioned in PR #8.

_Adding unit testing is definitely required - with continuous integration through Octave._

- [ ] make sure that metadata are returned properly

**Comment by Remi-Gau** [comment]
Will start looking into creating unit tests

**Comment by gllmflndn** [comment]
Thanks, there should be a webhook for Travis already. We can start by calling `bids.layout` on all the BIDS datasets from https://github.com/bids-standard/bids-examples and report errors.

**Comment by Remi-Gau** [comment]
yup. I was also checking how pybids does it for inspiration. seems that they have some dummy BIDS structure directly in the repo. We might have to do something like that for some things maybe. 
What do you say?

**Comment by Remi-Gau** [comment]
Also I am fairly new to unit testing and CI so I will do my best not to try your patience too much.

**Comment by gllmflndn** [comment]
I hijacked your PR #10 to implement a basic unit test framework with Travis and Octave.

In the future, we can decide to use [MATLAB](https://www.mathworks.com/help/matlab/matlab-unit-test-framework.html) and its [Cloud CI Service](https://mathworks.github.io/ci-pilot/) or use [MOxUnit](https://github.com/MOxUnit/MOxUnit).

For now, writing more `tests/test_*.m` files should be the priority. Sharing some tests with pybids might be useful.

**Comment by Remi-Gau** [comment]
Holy monkey you have been busy. Definitely bookmarking this this PR for future refs on how to do CI on a github repo! :-) 
Thank you SO MUCH for this.
I had started looking into the MOxUnit thing so what you did looks like black magic to me.

**Comment by apjanke** [comment]
If you'd like to see how this could be done with the Matlab Unit Test framework and MathWorks' CI Pilot program, I've put together a demo here: https://github.com/apjanke/bids-matlab-ut. This demo:

* ports the existing `tests/test_*.m` files to the Unit Test framework
* adds a few more tests
* adds CI integration hooks for Travis, CircleCI, and Azure Pipelines
* adds code coverage reporting using codecov.io.

Click on any of the build or codecov badges at the top of the README to see execution reports.

The downside is that the ported test definitions are not Octave-compatible. Would probably have to further port them to MOxUnit like gllmflndn suggested. (I'm not familiar with MOxUnit, so haven't done that already.) Or otherwise implement a Matlab-compatible Unit Test framework for Octave.
