### ISSUE TITLE
Behavior not consistent with BIDS validator

### ISSUE THREAD

**Issue by arnodelorme** [bids-standard/bids-matlab#96]
The attached file is from a valid dataset published on OpenNeuro (ds003195)
The import function fails with the error

Error using bids.util.tsvread>dsv_read (line 178)
Invalid DSV file '/data/matlab/dataquality/ds003195/participants.tsv': Varying number of delimiters per line.

Attaching the file

[participants.tsv.zip](https://github.com/bids-standard/bids-matlab/files/5539206/participants.tsv.zip)

**Comment by gllmflndn** [comment]
Thanks @arnodelorme, the file is:
```
participant_id<tab>sex<tab>	
sub-PLAC02<tab>1<tab>
sub-PLAC05<tab>1<tab>
```
i.e. `sprintf('participant_id\tsex\t\r\nsub-PLAC02\t1\t\r\nsub-PLAC05\t1\t\r\n')` so the issue here is with the trailing `<tab>`.

I am not sure whether it should be considered a valid TSV file. If it is then a fix could be to change l.146:
https://github.com/bids-standard/bids-matlab/blob/master/%2Bbids/%2Butil/tsvread.m#L146
so that it reads `hdr = deblank(S(1:h - 1));`

In any case, the error message is misleading as there are two tabs for all lines.

**Comment by arnodelorme** [comment]
I feel if it passes the BIDS validator (which apparently it does), then decoding should be possible.

**Comment by gllmflndn** [comment]
If that's the conclusion then I'm happy to fix the code as mentioned above but I wonder if the BIDS validator should be more strict here and declare this file as invalid.

Here is what the BIDS specs say about TSV files:
https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#tabular-files
and here is one of several TSV specs that can be found online (not accepting tabs in fields, therefore different than BIDS):
https://www.iana.org/assignments/media-types/text/tab-separated-values
From this, I would argue the file is not valid. Is it OK if I raise the issue in the `bids-validator` repository before deciding the fix to apply here?

**Comment by Remi-Gau** [comment]
Closing as this was changed in the validator a long time ago
