### ISSUE TITLE
Archived release of `bids-matlab` for referencing

### ISSUE THREAD

**Issue by jsheunis** [bids-standard/bids-matlab#98]
Hi everyone

I'd like to cite or refer to `bids-matlab` in a manuscript, and would prefer to refer to a specific release. Would it be possible to create a release for that purpose? I can of course fork the repo and create a release myself, but it would be better to refer to the main code base.

**Comment by Remi-Gau** [comment]
hey @jsheunis 

"Having releases" is on the agenda though the issue was that the API is not yet completely decided (AFAICT). See that other post: https://github.com/bids-standard/bids-matlab/issues/20#issuecomment-544551376

Things are set up to get our releases DOI minted on zenodo but we don't have a version 0.0.0 yet. The problem (as I understand it) is that with an underdefined API we might "iterate" through major version changes faster than my sleep debt accumulates because it would make backward compatibility very "brittle".

@gllmflndn @robertoostenveld 
I had literally just put "milestone and release date" as topic to discuss on the agenda for next week. Let me know what you think

**Comment by robertoostenveld** [comment]
perhaps we could start with some "alpha" releases of the current codebase?

**Comment by jsheunis** [comment]
I'd be happy with @robertoostenveld's suggestion, because the current version is what I've been using for a specific project, so having it archived for reproducibility purposes makes sense for this project. That said, I don't mind archiving a fork.

**Comment by Remi-Gau** [comment]
@jsheunis 

What is your deadline for this? 

At the last meeting we said we could do a quick and dirty, but we could try to have something cleaner if we have a later due date.

**Comment by jsheunis** [comment]
I ended up creating a forked release, since I was under some time pressure. This is fine for now, since it's for a preprint. But for updated versions of my project down the line it would be good to refer to the main `bids-matlab` repo. So I'd say, from my current perspective, something cleaner would be fine at a later stage (a couple of months from now).

**Comment by Remi-Gau** [comment]
OK that gives time to deliver something a bit less "alpha".

**Comment by Remi-Gau** [comment]
There is a first tagged release:
- https://github.com/bids-standard/bids-matlab/releases/tag/v0.1.0

And a DOI on zenodo:
- https://doi.org/10.5281/zenodo.5910584
